### ISSUE TITLE
Xcode 15 build error: Unsupported mach-o filetype (only MH_OBJECT and MH_DYLIB can be linked) in libLLVM.dylib

### ISSUE THREAD

**Issue by kyo-torstar** [Kumulos/KumulosSdkReactNative#49]
After upgrading my Xcode from 14.3 to 15.0, there is a compilation error "Unsupported mach-o filetype (only MH_OBJECT and MH_DYLIB can be linked) in libLLVM.dylib"

I look deeper it should be related to the Pod "KumulosKSCrash". There is file "llvm-config.h"

**Comment by cgwyllie** [comment]
Hi @kyo-torstar , this should now be addressed in our 8.0.0 release, please update and feel free to re-open if you continue to experience problems.
